# Datenanreicherung

Um geografische Analysen durchzuführen und eine Map der Künstlerstandorte zu erstellen, wurde der Datensatz mit Informationen über die Länder der Künstler angereichert. Dieser Prozess nutzte die `musicbrainz` Bibliothek, um Zugriff auf die MusicBrainz-Datenbank zu erhalten. Mit dieser Datenbank konnte ich anhand des Künstlernamens das Herkunftsland der Künstler herausfinden.



## Funktion zur Ermittlung des Künstlerlandes
Zuerst habe ich aus dem DataFrame der vorbereiteten Daten eine Liste der Künstlernamen extrahiert, die für die Abfragen nach Länderinformationen verwendet wurde. Anschließend habe ich eine Funktion implementiert, um das Land eines Künstlers mit Hilfe der [MusicBrainz API](https://musicbrainz.org/) zu finden. Diese Funktion behandelt auch Fehler und Fälle, in denen kein Land gefunden wurde.


Die Funktion `find_artist_country` dient dazu, das Land eines Künstlers zu ermitteln. Sie nutzt die [MusicBrainz API](https://musicbrainz.org/), um die notwendigen Informationen abzurufen. Die Funktion geht dabei wie folgt vor:

1. **Setzen des User-Agent**: Zuerst wird ein User-Agent für die MusicBrainz API gesetzt. Dies ist notwendig, um die Anfragen an die API zu authentifizieren (Account ist notwendig).

2. **Suchanfrage an MusicBrainz**: Die Funktion sucht nach dem übergebenen Künstlernamen.

3. **Rückgabe des Landes**: Wenn ein Künstler gefunden wird, gibt die Funktion das Land des Künstlers zurück.

4. **Fehlerbehandlung**: Im Falle eines Fehlers bei der Anfrage oder der Verarbeitung der Daten wird eine Fehlermeldung zurückgegeben.

```{python}
"""
def find_artist_country(artist_name):
    mb.set_useragent("Artist_Country", "1.0", contact="me@example.com")
    try:
        result = mb.search_artists(artist=artist_name, limit=1)
        if result['artist-list']:
            artist = result['artist-list'][0]
            country = artist['area']['name']
            return country
        else:
            return "Artist not found"
    except Exception as e:
        return f"Error: {e}"

"""

```

## Anreicherung des Datensatzes mit den Künstlerländern

Der Datensatz wurde mit den Ländern der Künstler angereichert, indem die zuvor definierte Funktion verwendet wurde, um das Land für jeden Künstler abzufragen und dem DataFrame hinzuzufügen. Das ganze habe ich mit einer for-Schleife realisiert.

```{python}
"""
artist_country_list = []

for artist in artist_list:
artist_country_list.append(find_artist_country(artist))

df['artist_country'] = artist_country_list

"""

```

Da die Datenbank leider nicht alle Künstler kannte, kam es in manchen Spalten zu Errors. Diese habe ich im Anschluss entfernt.


<br/>
<br/>

**Diese Datenanreicherung ermöglicht nun eine geografische Analyse der Künstlerstandorte und unterstützt die visuelle Darstellung der globalen Verteilung der Top-Künstler. Darauf basierend ist nun die Darstellung einer Map möglich.**
