# Fazit und Reflexion

## Projektergebnisse

Im Rahmen des Projekts konnten umfangreiche und aufschlussreiche Informationen über die Musik und die Musikindustrie gewonnen werden. Im folgenden werden die zentralen Erkenntnisse des Projekts zusammengefasst dargelegt, einschließlich der entscheidenden Faktoren, die einen Song zum Erfolg führen können.

Die **Tonart** und der **Key** eines Songs spielen eine große Rolle. Es ist darauf zu achten, dass die Tonart **Major** verwendet wird, das spricht für einen fröhlichen Klang. Außerdem sollte der Song den Key **C#** haben.

Eine Weitere wichtige Rolle spielt der **Releasemonat** des Songs. Die meisten Top-Songs wurden im **Januar** oder im **Mai** released. Im August wurden fast viermal so wenig Songs released wie in den beiden Top-Monaten.

Eine weitere Auffälligkeit ist, dass die meisten Top-Songs einen sehr **geringen Sprechanteil** haben. Also sollte sich der Musiker lieber auf Gesang und Melodie konzentrieren und weniger auf Sprechgesang bzw. Rap.

Zudem sollte der Song ein hohes Energieniveau haben und englisch- oder spanischsprachig sein.

**Geheimformel:**

$$
\begin{align*}
\text{Erfolg} &= \text{Tonart(Major)} + \text{Key(C\#)} \\
&+ \text{ReleaseMonat(Jan|Feb)} + \text{Speechiness(3\%)} \\
&+ \text{Energy(65\%)} + \text{Language(Englisch|Spanisch)}
\end{align*}
$$


## Reflexion

Die Reflexion dieses Projekts zeigt, wie eine datengetriebene Analyse Erfolgsfaktoren von Musik zeigen kann. Jedoch während bestimmte Trends, wie die Veröffentlichung in bestimmten Monaten oder die Verwendung eines speziellen Keys, die Erfolgschancen eines Hits verbessern, ist es dennoch wichtig zu betonen, dass Musik viel mehr als eine Sammlung von Datenpunkten ist. Musik ist und bleibt eine Kunstform und dies sollte meiner Meinung nach auch so bleiben. Es wäre doch sehr schade, wenn sich alle Songs gleich anhören würden und die verschiedenen Genres miteinander verschmelzen.

Deswegen sollte zu der Geheimformel des musikalischen Erfolgs noch Kreativität und musikalische Individualität hinzugefügt werden.