# Vorwort {.unnumbered}


Die Art und Weise, wie wir Musik konsumieren, hat sich in den letzten Jahren grundlegend geändert. Anstatt CDs und MP3-Player haben die meisten Menschen heute ein Abonnement bei einem Musikstreamingdienst. Dabei stellt sich die Frage, was ein Song braucht, um bei einem Streamingdienst Erfolg zu haben.

<br/>
Dieses Projekt wurde mit der Absicht ins Leben gerufen, diese Frage zu beantworten. Dafür wurde ein Datensatz der meist-gestreamtesten Songs im Jahre 2023, anhand verschiedener Merkmale analysiert, um eine Geheimformel für einen erfolgreichen Song zu finden. In der folgenden Dokumentation werde ich den Weg beschreiben, von der Beschaffung und Vorbereitung der Daten, über die Erstellung detaillierter Visualisierungen mit Altair, bis hin zur Entwicklung eines interaktiven Dashboards mit Streamlit. Dabei werde ich nicht nur auf die technischen Herausforderungen und die Lösungen derer eingehen, sondern auch die Ergebnisse klar darstellen.

<br/>

Falls Sie meine Ergebnisse anhand einer Präsentation oder einem interaktiven Dashboard einsehen möchten, finden Sie diese unter den folgenden Links:

- [Präsentation](https://laurenzbrahner.github.io/quarto_prasi/)
- [Dashboard](https://appapp-ka7buefabvnokhdfwhyptg.streamlit.app/)